// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingOnBoard.Context;

#nullable disable

namespace ParkingOnBoard.Migrations
{
    [DbContext(typeof(ParkingOnBoardContext))]
    [Migration("20230816081300_Remove_Property_TotalValidSlots_FromStreet")]
    partial class Remove_Property_TotalValidSlots_FromStreet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkingOnBoard.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Tirana"
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Berat"
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Skrapar"
                        });
                });

            modelBuilder.Entity("ParkingOnBoard.ParkingSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBusy")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("int");

                    b.Property<int>("StreetId")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StreetId");

                    b.ToTable("ParkingSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBusy = false,
                            IsClosed = false,
                            SlotNumber = 1,
                            StreetId = 1,
                            StreetName = "Naim Frasheri"
                        },
                        new
                        {
                            Id = 2,
                            IsBusy = false,
                            IsClosed = false,
                            SlotNumber = 2,
                            StreetId = 1,
                            StreetName = "Naim Frasheri"
                        },
                        new
                        {
                            Id = 3,
                            IsBusy = false,
                            IsClosed = false,
                            SlotNumber = 3,
                            StreetId = 3,
                            StreetName = "Antipatrea"
                        },
                        new
                        {
                            Id = 4,
                            IsBusy = false,
                            IsClosed = false,
                            SlotNumber = 4,
                            StreetId = 3,
                            StreetName = "Antipatrea"
                        },
                        new
                        {
                            Id = 5,
                            IsBusy = false,
                            IsClosed = false,
                            SlotNumber = 5,
                            StreetId = 3,
                            StreetName = "Antipatrea"
                        },
                        new
                        {
                            Id = 6,
                            IsBusy = false,
                            IsClosed = false,
                            SlotNumber = 6,
                            StreetId = 3,
                            StreetName = "Antipatrea"
                        },
                        new
                        {
                            Id = 7,
                            IsBusy = false,
                            IsClosed = false,
                            SlotNumber = 7,
                            StreetId = 2,
                            StreetName = "Sami Frasheri"
                        },
                        new
                        {
                            Id = 8,
                            IsBusy = false,
                            IsClosed = false,
                            SlotNumber = 8,
                            StreetId = 2,
                            StreetName = "Sami Frasheri"
                        });
                });

            modelBuilder.Entity("ParkingOnBoard.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasTwoSides")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Streets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CityName = "Tirana",
                            HasTwoSides = false,
                            IsClosed = false,
                            Name = "Naim Frasheri"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            CityName = "Tirana",
                            HasTwoSides = false,
                            IsClosed = false,
                            Name = "Sami Frasheri"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            CityName = "Berat",
                            HasTwoSides = true,
                            IsClosed = false,
                            Name = "Antipatrea"
                        });
                });

            modelBuilder.Entity("ParkingOnBoard.ParkingSlot", b =>
                {
                    b.HasOne("ParkingOnBoard.Street", "Street")
                        .WithMany("Slots")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Street");
                });

            modelBuilder.Entity("ParkingOnBoard.Street", b =>
                {
                    b.HasOne("ParkingOnBoard.Models.City", null)
                        .WithMany("Streets")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParkingOnBoard.Models.City", b =>
                {
                    b.Navigation("Streets");
                });

            modelBuilder.Entity("ParkingOnBoard.Street", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
